plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.serialization"
    id "com.android.library"
}

apply from: "$mppProjectWithSerialization"


kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api project(":kroles.roles")
                api libs.microutils.repos.common
                api libs.microutils.repos.cache
                api libs.kslog
            }
        }
    }
}
