project.version = "$version"
project.group = "$group"

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation libs.kotlin
                api libs.kotlin.serialization
            }
        }
        commonTest {
            dependencies {
                implementation libs.kotlin.test.common
                implementation libs.kotlin.test.annotations.common
            }
        }
    }
}
